// TypeScript mirrors of ui/card_models.py.
// Phase 1 only types the cards we render; the rest are typed as a generic
// fallback so the canvas still renders unknown-card-type placeholders.

export type CardBase = {
  id: string; // generated by backend streaming layer
  card_type: string;
  title: string;
  subtitle?: string | null;
  submit_label?: string;
};

export type BalanceViewCard = CardBase & {
  card_type: "balance_view";
  total_balance: number;
  vested_balance: number;
  accounts: { plan_name: string; type: string; balance: number; vested_balance: number }[];
};

export type AllocationFormCard = CardBase & {
  card_type: "allocation_form";
  account_id: string;
  account_label: string;
  funds: { ticker: string; name: string; current_pct: number; target_pct: number }[];
};

export type ConfirmationCard = CardBase & {
  card_type: "confirmation";
  diff?: { field: string; before: string; after: string }[];
  summary_lines?: string[];
};

export type SuccessCard = CardBase & {
  card_type: "success";
  request_id?: string | null;
  summary_lines?: string[];
};

export type UnknownCard = CardBase & {
  card_type: string;
  [k: string]: unknown;
};

export type AnyCard = BalanceViewCard | AllocationFormCard | ConfirmationCard | SuccessCard | UnknownCard;

// Layout entry persisted with the card data
export type CardLayout = {
  i: string; // card id
  x: number;
  y: number;
  w: number;
  h: number;
};

export type CanvasCard = {
  card: AnyCard;
  layout: CardLayout;
};

export type SessionMeta = {
  thread_id: string;
  title: string | null;
  updated_at: string;
};

export type SavedSessionState = {
  thread_id: string;
  title: string | null;
  cards: CanvasCard[];
  messages: { role: string; content: string }[];
};
